version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "5173:5173"
    tty: true
    command: sh -c "npm run dev"
